import {properties} from './u1-data.mjs?v=20261004-r2';
import {makeConversion,makeDensity,fixedPractice as legacyPractice} from './engine.mjs?v=20261004-r2';
const choose=(lang,es,eu)=>lang==='cast'?es:eu;
const field=(id,label,accepted,solution,reason,lang)=>({id,kind:'word',prompt:choose(lang,...label),accepted,solution:choose(lang,...solution),steps:[choose(lang,...reason)]});
const group=(id,topic,prompt,fields,lang,source='')=>({id,topic,kind:'multi',prompt:choose(lang,...prompt),fields,source,solution:fields.map(f=>f.solution).join('; '),steps:[]});
export function bookExercises(lang='cast',topic=0){
 const es=lang==='cast',legacy=legacyPractice(lang);
 if(topic===0){
  const materials=[['Lápiz','Arkatza',true],['Música','Musika',false],['Archivo MP3 como información','MP3 fitxategia informazio gisa',false],['Dióxido de carbono','Karbono dioxidoa',true],['Escritura como información','Idazkera informazio gisa',false],['Gato','Katua',true],['Río','Ibaia',true],['Luz','Argia',false],['Arena','Hondarra',true],['Algodón','Kotoia',true]];
  const matter=group('book-matter',0,['Indica si cada elemento es materia: responde sí o no en cada apartado. Distingue la información escrita o digital de su soporte físico.','Adierazi elementu bakoitza materia den: erantzun bai edo ez atal bakoitzean. Bereizi idatzizko edo informazio digitala euskarri fisikotik.'],materials.map(([a,b,yes],i)=>field('matter-'+i,[a,b],yes?['sí','si','bai']:['no','ez'],yes?['Sí','Bai']:['No','Ez'],yes?['Tiene masa y ocupa volumen.','Masa du eta bolumena hartzen du.']:i===2||i===4?['El contenido es información; su soporte físico sí es material.','Edukia informazioa da; euskarri fisikoa materiala da.']:['Es un fenómeno energético, no una sustancia material.','Energia fenomenoa da, ez substantzia materiala.'],lang)),lang,'PDF 7–8');
  const bodies=[['Libro','Liburua',true],['Zumo','Zukua',false],['Botella de agua (el recipiente)','Ur botila (ontzia)',true],['Teléfono','Telefonoa',true],['Aire','Airea',false],['Pájaro','Txoria',true],['Mercurio líquido','Merkurio likidoa',false],['Atmósfera','Atmosfera',false],['Avión','Hegazkina',true],['Luna','Ilargia',true]];
  const body=group('book-bodies',0,['Clasifica los diez elementos como cuerpo o sistema material, siguiendo el criterio del temario.','Sailkatu hamar elementuak gorputz edo sistema material gisa, temarioaren irizpidea jarraituz.'],bodies.map(([a,b,yes],i)=>field('body-'+i,[a,b],yes?['cuerpo','cuerpo material','gorputza','gorputz','gorputz materiala']:['sistema','sistema material','sistema materiala'],yes?['Cuerpo material','Gorputz materiala']:['Sistema material','Sistema materiala'],yes?['Tiene límites definidos en esta clasificación escolar.','Muga zehatzak ditu eskolako sailkapen honetan.']:['El temario clasifica líquidos y gases como sistemas materiales.','Temarioak likidoak eta gasak sistema material gisa sailkatzen ditu.'],lang)),lang,'PDF 9–10');
  const changes=group('review-changes',0,['Clasifica los ocho cambios: físico o químico.','Sailkatu zortzi aldaketak: fisikoa edo kimikoa.'],[['Derretir hielo','Izotza urtzea',false],['Quemar papel','Papera erretzea',true],['Cortar papel','Papera moztea',false],['Oxidar hierro','Burdina oxidatzea',true],['Evaporar agua','Ura lurruntzea',false],['Congelar agua','Ura izoztea',false],['Fundir cera','Argizaria urtzea',false],['Quemar cera','Argizaria erretzea',true]].map(([a,b,c],i)=>field('change-'+i,[a,b],c?['químico','quimico','cambio químico','kimikoa','aldaketa kimikoa']:['físico','fisico','cambio físico','fisikoa','aldaketa fisikoa'],c?['Químico','Kimikoa']:['Físico','Fisikoa'],c?['Aparecen sustancias nuevas: cambia la composición.','Substantzia berriak agertzen dira: osaera aldatzen da.']:['Se mantiene la sustancia; cambia forma, tamaño o estado.','Substantzia mantentzen da; forma, tamaina edo egoera aldatzen da.'],lang)),lang,'Repaso PDF 3–4');
  return [matter,body,changes];
 }
 if(topic===1){
  const propertyFields=legacy.filter(e=>e.kind==='property' && e.id!=='property-0');
  const props=group('book-properties',1,['Clasifica las ocho propiedades. Escribe tres etiquetas por fila: cuantitativa o cualitativa; intensiva o extensiva; general o característica.','Sailkatu zortzi propietateak. Idatzi hiru etiketa lerro bakoitzeko: kuantitatiboa edo kualitatiboa; intentsiboa edo estentsiboa; orokorra edo bereizgarria.'],propertyFields.map((e,i)=>({...e,prompt:properties[i+1].name[es?0:1]})),lang,'PDF 15–16');
  const passage=choose(lang,'El aceite es un líquido amarillo insoluble en agua. Su densidad (0,9 g/cm³) es menor que la del agua (1 g/cm³), por eso flota sobre ella. En un vaso con 150 cm³ de agua añadimos 10 cm³ de aceite; la mezcla está a 20 °C.','Olioa uretan disolbaezina den likido horia da. Olioaren dentsitatea (0,9 g/cm³) urarena (1 g/cm³) baino txikiagoa da; horregatik, uraren gainean flotatzen du. 150 cm³ ur dituen edalontzi batean 10 cm³ olio jarri ditugu, eta nahastearen tenperatura 20 °C da.');
  const oil=group('book-oil',1,['Lee el texto completo e identifica las propiedades mencionadas en los seis apartados.','Irakurri testu osoa eta identifikatu aipatutako propietateak sei ataletan.'],[
   field('oil-state',['¿Qué propiedad expresa «líquido»?','Zer propietatek adierazten du «likidoa»?'],['estado','estado físico','estado de agregación','egoera','egoera fisikoa','agregazio egoera'],['Estado físico: líquido','Egoera fisikoa: likidoa'],['Indica el estado de agregación del aceite.','Olioaren agregazio egoera adierazten du.'],lang),
   field('oil-color',['¿Qué propiedad expresa «amarillo»?','Zer propietatek adierazten du «horia»?'],['color','kolorea','kolore'],['Color: amarillo','Kolorea: horia'],['Describe una cualidad del aceite.','Olioaren nolakotasuna deskribatzen du.'],lang),
   field('oil-solubility',['¿Qué propiedad expresa «insoluble en agua»?','Zer propietatek adierazten du «uretan disolbaezina»?'],['solubilidad','disolbagarritasuna','disolbagarritasun'],['Solubilidad en agua','Uretako disolbagarritasuna'],['Indica que aceite y agua no forman una disolución.','Olioak eta urak ez dutela disoluzioa osatzen adierazten du.'],lang),
   field('oil-density',['¿Qué propiedad se expresa en g/cm³?','Zer propietate adierazten da g/cm³-tan?'],['densidad','dentsitatea','dentsitate'],['Densidad: aceite 0,9; agua 1 g/cm³','Dentsitatea: olioa 0,9; ura 1 g/cm³'],['Relaciona masa y volumen; explica qué capa queda arriba.','Masa eta bolumena lotzen ditu; zein geruza geratzen den gainean azaltzen du.'],lang),
   field('oil-volume',['¿Qué propiedad expresan 150 cm³ y 10 cm³?','Zer propietatek adierazten dituzte 150 cm³ eta 10 cm³?'],['volumen','bolumena','bolumen'],['Volumen','Bolumena'],['Miden espacio ocupado por cada líquido.','Likido bakoitzak hartutako espazioa neurtzen dute.'],lang),
   field('oil-temperature',['¿Qué propiedad expresa 20 °C?','Zer propietatek adierazten du 20 °C?'],['temperatura','tenperatura'],['Temperatura','Tenperatura'],['Es temperatura actual, no temperatura de ebullición.','Uneko tenperatura da, ez irakite tenperatura.'],lang)
  ],lang,'PDF 17');oil.passage=passage;
  const columns=group('book-six-columns',1,['Completa la tabla del temario: para cada propiedad, marca una casilla en cada una de las tres parejas de columnas. Cada propiedad pertenece a tres columnas.','Osatu temarioko taula: propietate bakoitzeko, markatu laukitxo bat hiru zutabe bikoteetako bakoitzean. Propietate bakoitza hiru zutabetan dago.'],propertyFields.map((e,i)=>({...e,id:'table-'+i,prompt:properties[i+1].name[es?0:1],kind:'property-choice'})),lang,'PDF 18');
  return [props,oil,columns];
 }
 if(topic===2){
  const tasks=[[.08,'kg','mg'],[5.7,'dag','cg'],[548,'dg','hg'],[37,'mg','kg'],[7.5,'dam3','L'],[875,'mL','dm3'],[.00065,'km3','m3'],[378,'dm3','L'],[805,'cL','hL'],[.35,'daL','dL'],[2.5,'L','mL'],[48,'mL','daL']];
  const convert=(number,start)=>group('book-'+number,2,[`Ejercicio ${number}: realiza las cuatro conversiones. Escribe cada resultado con su unidad final.`,`${number}. ariketa: egin lau bihurketak. Idatzi emaitza bakoitza azken unitatearekin.`],tasks.slice(start,start+4).map(([v,f,t],i)=>({...makeConversion(v,f,t,lang),id:`book-${number}-${i}`})),lang,'PDF 30');
  return [convert(68,0),{...legacy.find(e=>e.id==='order-length'),id:'book-69',source:'PDF 30 · 69'},{...legacy.find(e=>e.id==='order-area'),id:'book-70',source:'PDF 30 · 70'},convert(71,4),convert(72,8)];
 }
 const compare=group('book-density-comparison',3,['Responde a las comparaciones del temario. Escribe «igual» o «hierro» según el apartado.','Erantzun temarioko konparazioei. Idatzi «berdina» edo «burdina», atalaren arabera.'],[
  field('compare-mass',['¿Qué tiene más masa: 1 kg de hierro o 1000 g de plumas?','Zerk du masa handiagoa: 1 kg burdinak edo 1000 g lumak?'],['igual','iguales','misma masa','tienen la misma masa','berdina','berdinak','masa bera'],['Igual: 1 kg = 1000 g','Berdina: 1 kg = 1000 g'],['La unidad cambia, la masa real es igual. Las plumas ocupan más volumen.','Unitatea aldatzen da, benetako masa bera da. Lumek bolumen handiagoa hartzen dute.'],lang),
  field('compare-box',['Dos cajas de igual volumen contienen hierro (5 kg) y plumas (0,2 kg). ¿Cuál tiene más masa?','Bolumen bereko bi kutxek burdina (5 kg) eta lumak (0,2 kg) dituzte. Zeinek du masa handiagoa?'],['hierro','la de hierro','burdina','burdinarena'],['Hierro: 5 kg > 0,2 kg','Burdina: 5 kg > 0,2 kg'],['Con igual volumen, más masa significa mayor densidad.','Bolumen bera izanda, masa handiagoak dentsitate handiagoa esan nahi du.'],lang),
  {id:'compare-ratio',kind:'number',prompt:choose(lang,'¿Cuántas veces es mayor la densidad de la caja de hierro? Escribe el factor con unidad «veces».','Zenbat aldiz handiagoa da burdinaren kutxaren dentsitatea? Idatzi faktorea «aldiz» unitatearekin.'),result:25,unit:es?'veces':'aldiz',solution:es?'25 veces':'25 aldiz',steps:['5 / 0,2 = 25',choose(lang,'Los volúmenes son iguales; el cociente de densidades es el de masas.','Bolumenak berdinak dira; dentsitateen zatidura masena da.')]}
 ],lang,'PDF 32–34');
 const density=['density','mass','volume'].map(mode=>({...makeDensity(mode,2,30,lang),source:'Práctica de fórmulas · PDF 35'}));
 const floating=group('review-floating',3,['Compara con agua de densidad 1 g/cm³. Escribe «flota», «se hunde» o «suspendido». Usa la densidad media de cada objeto.','Alderatu 1 g/cm³-ko dentsitatea duen urarekin. Idatzi «flotatzen du», «hondoratzen da» edo «esekita». Erabili objektu bakoitzaren batez besteko dentsitatea.'],[[.8,'float'],[1.2,'sink'],[1,'equal']].map(([d,k],i)=>field('floating-'+i,[`Objeto ${i+1}: densidad media ${String(d).replace('.',',')} g/cm³.`,`${i+1}. objektua: batez besteko dentsitatea ${String(d).replace('.',',')} g/cm³.`],k==='float'?['flota','flotar','flotatzen du','flotatu']:k==='sink'?['se hunde','hunde','hundirse','hondoratzen da','hondoratu']:['suspendido','queda suspendido','esekita','esekita geratzen da'],k==='float'?['Flota','Flotatzen du']:k==='sink'?['Se hunde','Hondoratzen da']:['Suspendido','Esekita'],[d<1?'Menor densidad media que el agua.':d>1?'Mayor densidad media que el agua.':'Igual densidad; posible equilibrio en el modelo sencillo.',d<1?'Ura baino batez besteko dentsitate txikiagoa.':d>1?'Ura baino batez besteko dentsitate handiagoa.':'Dentsitate bera; oreka posiblea eredu sinplean.'],lang)),lang,'Repaso PDF 31, 36–37');
 return [compare,...density,{...makeDensity('density',2,500,lang,true),source:'Práctica con unidades compatibles'},floating];
}
