import {baseUnits,properties} from './u1-data.mjs';
import {conversionTasks,makeConversion,makeDensity,fmt,prettyUnit} from './engine.mjs';

export function questionBank(lang='cast') {
  const cast=lang==='cast', l=cast?0:1, bank=[];
  const add=(level,topic,prompt,options,explanation)=>bank.push({id:`u1-l${level}-${bank.filter(q=>q.level===level).length+1}`,level,topic,prompt,options,correct:0,explanation});
  const pair=(level,topic,es,eu)=>add(level,topic,...(cast?es:eu));

  baseUnits.forEach((u,i)=>{
    const others=baseUnits.filter((v,j)=>j!==i).slice(0,3).map(v=>v[2]);
    add(1,2,cast?`¿Cuál es la unidad básica SI de ${u[0].toLowerCase()}?`:`Zein da ${u[1].toLowerCase()} magnitudearen SIko oinarrizko unitatea?`,[u[2],...others],cast?`${u[0]} se expresa en ${u[3].toLowerCase()} (${u[2]}). Cada magnitud tiene su unidad.`:`${u[1]}: ${u[4]} (${u[2]}). Magnitude bakoitzak bere unitatea du.`);
  });
  const definitions=[
    [0,['¿Qué caracteriza a la materia?',['Tiene masa y ocupa volumen','Tiene luz y produce sonido','Siempre se ve y es sólida','Siempre se mueve y calienta'],'La materia puede ser sólida, líquida o gaseosa: tiene masa y ocupa volumen.'],['Zerk definitzen du materia?',['Masa du eta bolumena hartzen du','Argia du eta soinua sortzen du','Beti ikusgarria eta solidoa da','Beti mugitzen eta berotzen da'],'Materia solidoa, likidoa edo gasa izan daiteke: masa du eta bolumena hartzen du.']],
    [0,['¿Qué distingue un cambio químico?',['Se forman sustancias nuevas','Solo cambia el tamaño','Solo cambia la forma','Solo cambia la ubicación'],'La formación de sustancias nuevas indica un cambio de composición.'],['Zerk bereizten du aldaketa kimikoa?',['Substantzia berriak sortzen dira','Tamaina bakarrik aldatzen da','Forma bakarrik aldatzen da','Kokapena bakarrik aldatzen da'],'Substantzia berriak sortzeak osaera aldatzen dela adierazten du.']],
    [0,['En un cambio físico…',['Se mantiene la sustancia','Siempre aparece una sustancia','La masa deja de existir','Nunca cambia el estado'],'Puede cambiar la forma o el estado sin cambiar la sustancia.'],['Aldaketa fisiko batean…',['Substantzia bera mantentzen da','Beti substantzia berria sortzen da','Masa desagertu egiten da','Egoera ez da inoiz aldatzen'],'Forma edo egoera aldatu daiteke, substantzia aldatu gabe.']],
    [0,['¿Qué respalda una explicación científica?',['Pruebas que pueden contrastarse','Una opinión sin comprobación','Una tradición sin observaciones','Una suposición imposible de probar'],'Las observaciones y experimentos permiten comprobar las explicaciones.'],['Zerk babesten du azalpen zientifikoa?',['Egiaztatu daitezkeen frogek','Egiaztapenik gabeko iritziak','Behaketarik gabeko tradizioak','Frogatu ezin den usteak'],'Behaketek eta esperimentuek azalpenak egiaztatzeko balio dute.']],
    [0,['¿Qué ejemplo tiene límites definidos?',['Un libro sobre la mesa','El aire de la atmósfera','El agua que fluye en un río','El gas que sale de una válvula'],'El libro es el ejemplo de cuerpo material con límites definidos del temario.'],['Zein adibidek ditu muga zehatzak?',['Mahai gaineko liburu batek','Atmosferako aireak','Ibaian doan urak','Balbulatik ateratzen den gasak'],'Liburua muga zehatzak dituen gorputz materialaren adibidea da temarioan.']],
    [1,['Una propiedad cuantitativa…',['Puede expresarse con una medida','Describe solo una impresión','Nunca utiliza ningún número','Solo puede aplicarse al color'],'Una medida cuantitativa incluye un valor numérico y, cuando corresponde, una unidad.'],['Propietate kuantitatibo bat…',['Neurri baten bidez adierazten da','Iritzi bat bakarrik deskribatzen du','Ez du inoiz zenbakirik erabiltzen','Koloreari bakarrik aplikatzen zaio'],'Neurri kuantitatiboak zenbakizko balioa eta, dagokionean, unitatea ditu.']],
    [1,['Una propiedad cualitativa describe…',['Una cualidad como el color','Una masa medida en gramos','Un volumen medido en litros','Una longitud medida en metros'],'El color blanco es una descripción cualitativa en esta unidad.'],['Propietate kualitatiboak deskribatzen du…',['Kolorea bezalako nolakotasuna','Gramotan neurtutako masa','Litrotan neurtutako bolumena','Metrotan neurtutako luzera'],'Kolore zuria deskribapen kualitatiboa da unitate honetan.']],
    [1,['Una propiedad extensiva…',['Depende de la cantidad de materia','No depende de la cantidad','Identifica siempre la sustancia','Nunca puede medirse con números'],'Masa y volumen aumentan al aumentar la cantidad de muestra.'],['Propietate estentsibo bat…',['Materia kantitatearen araberakoa da','Ez da kantitatearen araberakoa','Beti substantzia identifikatzen du','Ez da zenbakiekin neurtzen'],'Masa eta bolumena handitzen dira lagin kantitatea handitzean.']],
    [1,['Una propiedad intensiva…',['No depende de la cantidad de muestra','Se duplica siempre al partir la muestra','Es siempre una propiedad cualitativa','Solo se aplica a muestras de gases'],'La densidad se mantiene en muestras de la misma sustancia bajo las mismas condiciones.'],['Propietate intentsibo bat…',['Ez da lagin kantitatearen araberakoa','Beti bikoizten da lagina zatitzean','Beti propietate kualitatiboa da','Gas laginetan bakarrik erabiltzen da'],'Dentsitatea mantentzen da substantzia beraren laginetan, baldintza beretan.']],
    [1,['Una propiedad característica ayuda a…',['Identificar una sustancia','Contar cualquier recipiente','Cambiar la cantidad de materia','Elegir el tamaño de la muestra'],'La densidad o la temperatura de ebullición ayudan a distinguir sustancias en condiciones fijadas.'],['Propietate bereizgarriak laguntzen du…',['Substantzia bat identifikatzen','Edozein ontzi zenbatzen','Materia kantitatea aldatzen','Laginaren tamaina aukeratzen'],'Dentsitateak edo irakite tenperaturak substantziak bereizten laguntzen dute baldintza jakinetan.']],
    [2,['¿Qué es medir?',['Comparar con una unidad de referencia','Adivinar sin utilizar referencias','Observar solo el color de un objeto','Cambiar de sustancia al experimentar'],'Para medir necesitamos una magnitud y una unidad de referencia.'],['Zer da neurtzea?',['Erreferentzia unitate batekin alderatzea','Erreferentziarik gabe asmatzea','Objektuaren kolorea bakarrik ikustea','Esperimentuan substantzia aldatzea'],'Neurtzeko magnitude bat eta erreferentzia unitate bat behar ditugu.']],
    [2,['¿Qué es una magnitud?',['Una propiedad que se puede medir','Una opinión que no se contrasta','Una unidad sin ninguna propiedad','Una sustancia que cambia de estado'],'Longitud, masa y tiempo son magnitudes porque se pueden medir.'],['Zer da magnitude bat?',['Neurtu daitekeen propietate bat','Egiaztatzen ez den iritzi bat','Propietaterik gabeko unitate bat','Egoera aldatzen duen substantzia bat'],'Luzera, masa eta denbora magnitudeak dira, neurtu daitezkeelako.']],
    [3,['¿Cuál es la fórmula de la densidad?',['d = m / V','d = m × V','d = V / m','d = m + V'],'La densidad relaciona la masa con el volumen ocupado.'],['Zein da dentsitatearen formula?',['d = m / V','d = m × V','d = V / m','d = m + V'],'Dentsitateak masa eta hartutako bolumena erlazionatzen ditu.']]
  ];
  definitions.forEach(([topic,es,eu])=>pair(1,topic,es,eu));

  const matter=[['Aire','Airea',true],['Luz','Argia',false],['Humo','Kea',true],['Música','Musika',false],['Dióxido de carbono','Karbono dioxidoa',true],['Algodón','Kotoia',true],['Arena','Harea',true],['Pereza','Alferkeria',false]];
  matter.forEach(([es,eu,isMatter])=>add(2,0,cast?`Clasifica: ${es.toLowerCase()}.`:`Sailkatu: ${eu.toLowerCase()}.`,cast?(isMatter?['Es materia: masa y volumen','No es materia: no es sustancia','Es materia: solo si se ve','No es materia: solo por su forma']:['No es materia: no es sustancia','Es materia: masa y volumen','Es materia: solo si se oye','No es materia: porque pesa poco']):(isMatter?['Materia da: masa eta bolumena','Ez da materia: ez da substantzia','Materia da: ikusten bada bakarrik','Ez da materia: formagatik bakarrik']:['Ez da materia: ez da substantzia','Materia da: masa eta bolumena','Materia da: entzuten bada bakarrik','Ez da materia: masa txikiagatik']),cast?(isMatter?'Tiene masa y ocupa un volumen, aunque no siempre sea visible.':'No es una sustancia que tenga masa y volumen. El soporte material es una cosa distinta.'):(isMatter?'Masa du eta bolumena hartzen du, beti ikusgarria ez bada ere.':'Ez da masa eta bolumena dituen substantzia. Euskarri materiala beste gauza bat da.')));
  const changes=[['Derretir hielo','Izotza urtzea',false],['Quemar papel','Papera erretzea',true],['Cortar papel','Papera moztea',false],['Oxidar hierro','Burdina oxidatzea',true],['Evaporar agua','Ura lurruntzea',false],['Congelar agua','Ura izoztea',false],['Quemar cera','Argizaria erretzea',true],['Fundir cera','Argizaria urtzea',false]];
  changes.forEach(([es,eu,chemical])=>{
    const options=cast?['Químico: aparecen sustancias nuevas','Físico: se mantiene la sustancia','Químico: cambia solo el tamaño','Físico: aparece una sustancia nueva']:['Kimikoa: substantzia berriak sortzen dira','Fisikoa: substantzia bera mantentzen da','Kimikoa: tamaina bakarrik aldatzen da','Fisikoa: substantzia berria sortzen da'];
    if(!chemical)[options[0],options[1]]=[options[1],options[0]];
    add(2,0,cast?`¿Cómo clasificarías ${es.toLowerCase()}?`:`Nola sailkatuko zenuke ${eu.toLowerCase()}?`,options,cast?(chemical?'La composición cambia: se producen sustancias distintas.':'La forma o el estado cambia, pero sigue siendo la misma sustancia.'):(chemical?'Osaera aldatzen da: substantzia desberdinak sortzen dira.':'Forma edo egoera aldatzen da, baina substantzia bera da.'));
  });
  [['longitud','luzera','regla','erregela'],['masa','masa','balanza','balantza'],['tiempo','denbora','cronómetro','kronometroa'],['temperatura','tenperatura','termómetro','termometroa']].forEach(([es,eu,inst,euinst])=>{
    const instruments=cast?['regla','balanza','cronómetro','termómetro']:['erregela','balantza','kronometroa','termometroa'],correct=cast?inst:euinst;
    add(2,2,cast?`¿Qué instrumento mide ${es}?`:`Zein tresnak neurtzen du ${eu}?`,[correct,...instruments.filter(v=>v!==correct)],cast?`Para medir ${es}, utilizamos este instrumento: ${inst}.`:`${eu} neurtzeko ${euinst} erabiltzen dugu.`);
  });

  const labels=cast?[['Cuantitativa','Cualitativa'],['Intensiva','Extensiva'],['General','Característica']]:[['Kuantitatiboa','Kualitatiboa'],['Intentsiboa','Estentsiboa'],['Orokorra','Bereizgarria']];
  for(const dimension of ['type','amount']) properties.forEach(p=>{
    const d=dimension==='type'?0:1,index=p[dimension],wrong=labels[d][1-index];
    const suffix=cast?(d===0?'¿Se mide o describe una cualidad?':'¿Depende de la cantidad?'):(d===0?'Neurria ala nolakotasuna da?':'Kantitatearen araberakoa da?');
    const extras=cast?(d===0?['Solo puede clasificarse si es sólida','Ninguna: no es una propiedad']:['Solo depende del recipiente','Ninguna: no es una propiedad']):(d===0?['Solidoa bada bakarrik sailkatzen da','Bat ere ez: ez da propietatea']:['Ontziaren araberakoa bakarrik da','Bat ere ez: ez da propietatea']);
    const explanation=cast?(d===0?(index===0?'Se expresa con un valor medido; la dureza se trata mediante escalas en el temario.':'Describe una cualidad, sin una medida numérica en esta clasificación.'):(index===0?'No cambia por aumentar la cantidad de la misma sustancia en iguales condiciones.':'Cambia cuando cambia la cantidad de muestra.')):(d===0?(index===0?'Neurtutako balioz adierazten da; gogortasuna eskalen bidez lantzen da temarioan.':'Nolakotasun bat deskribatzen du, zenbakizko neurririk gabe sailkapen honetan.'):(index===0?'Ez da aldatzen substantzia beraren kantitatea handitzean, baldintza beretan.':'Lagin kantitatea aldatzean aldatzen da.'));
    add(3,1,`${p.name[l]}. ${suffix}`,[labels[d][index],wrong,...extras],explanation);
  });
  [properties[0],properties[3],properties[5],properties[6]].forEach(p=>add(3,1,cast?`¿Cómo se clasifica ${p.name[0].toLowerCase()} respecto a la identificación?`:`Nola sailkatzen da ${p.name[1].toLowerCase()} identifikazioari dagokionez?`,[labels[2][p.identity],labels[2][1-p.identity],...(cast?['Solo depende del número de muestras','No pertenece a ninguna clasificación']:['Lagin kopuruaren araberakoa bakarrik','Ez dagokio sailkapen bati ere'])],cast?(p.identity?'Ayuda a identificar sustancias comparadas bajo condiciones fijadas.':'No basta para identificar una sustancia: materiales diferentes pueden compartir ese valor.'):(p.identity?'Baldintza jakinetan substantziak identifikatzen laguntzen du.':'Ez da nahikoa substantzia identifikatzeko: material desberdinek balio bera izan dezakete.')));

  conversionTasks.forEach(([n,from,to])=>{
    const exercise=makeConversion(n,from,to,lang),unit=prettyUnit(to);
    add(4,2,exercise.prompt,[exercise.result,exercise.result*10,exercise.result/10,exercise.result*100].map(v=>`${fmt(v)} ${unit}`),exercise.steps.join(' · '));
  });
  ['density','mass','volume'].forEach(mode=>{
    const e=makeDensity(mode,2,30,lang);
    add(4,3,e.prompt,[e.result,e.result*2,e.result/2,e.result*4].map(v=>`${fmt(v)} ${prettyUnit(e.unit)}`),e.steps.join(' · '));
  });
  pair(4,2,['¿A qué equivale 1 L?',['1 dm³','1 m³','1 cm³','1 mm³'],'1 L = 1 dm³. Por tanto, 1 m³ = 1000 L.'],['Zeren baliokidea da 1 L?',['1 dm³','1 m³','1 cm³','1 mm³'],'1 L = 1 dm³. Beraz, 1 m³ = 1000 L.']);
  pair(4,3,['¿A qué equivale 1 g/cm³?',['1000 kg/m³','1 kg/m³','0,001 kg/m³','100 kg/m³'],'1 g = 0,001 kg y 1 cm³ = 0,000001 m³. Al dividir: 1000 kg/m³.'],['Zeren baliokidea da 1 g/cm³?',['1000 kg/m³','1 kg/m³','0,001 kg/m³','100 kg/m³'],'1 g = 0,001 kg eta 1 cm³ = 0,000001 m³. Zatitzean: 1000 kg/m³.']);

  properties.forEach(p=>{
    const indexes=[p.type,p.amount,p.identity];
    const triples=[indexes,[1-p.type,p.amount,p.identity],[p.type,1-p.amount,p.identity],[p.type,p.amount,1-p.identity]].map(a=>a.map((n,j)=>labels[j][n]).join(' · '));
    add(5,1,cast?`Elige la clasificación completa de ${p.name[0].toLowerCase()}.`:`Aukeratu ${p.name[1].toLowerCase()} propietatearen sailkapen osoa.`,triples,cast?'Las tres etiquetas responden a preguntas independientes: medida, cantidad e identificación.':'Hiru etiketek galdera independenteei erantzuten diete: neurria, kantitatea eta identifikazioa.');
  });
  const reasoning=[
    [0,['En una vela encendida, ¿qué dos procesos distinguimos?',['Fundir: físico; arder: químico','Fundir: químico; arder: físico','Ambos físicos: solo cambia la forma','Ambos químicos: siempre hay llama'],'La fusión mantiene la cera; la combustión produce nuevas sustancias.'],['Piztutako kandela batean, zein bi prozesu bereizten ditugu?',['Urtzea: fisikoa; erretzea: kimikoa','Urtzea: kimikoa; erretzea: fisikoa','Biak fisikoak: forma bakarrik aldatzen da','Biak kimikoak: beti sugarra dago'],'Urtzean argizaria mantentzen da; erretzean substantzia berriak sortzen dira.']],
    [0,['El aire no se ve. ¿Qué prueba que es materia?',['Tiene masa y llena un volumen','Que siempre cambia de color','Que no puede comprimirse nunca','Que tiene forma propia fija'],'Ser visible no es requisito: un gas tiene masa y ocupa espacio.'],['Airea ez da ikusten. Zerk frogatzen du materia dela?',['Masa du eta bolumena betetzen du','Beti kolorea aldatzen duela','Ezin dela inoiz konprimitu','Bere forma finko propioa duela'],'Ikusgarria izatea ez da baldintza: gas batek masa du eta espazioa hartzen du.']],
    [1,['Partimos agua homogénea en dos, sin cambiar condiciones. ¿Qué ocurre?',['Menos masa por parte, misma densidad','Misma masa por parte, doble densidad','Menos masa por parte, doble densidad','Misma masa por parte, menor densidad'],'Masa y volumen disminuyen a la vez, y su cociente se mantiene.'],['Ur homogeneoa bitan zatitzen dugu, baldintzak aldatu gabe. Zer gertatzen da?',['Masa txikiagoa zati bakoitzean, dentsitate bera','Masa bera zati bakoitzean, dentsitate bikoitza','Masa txikiagoa zati bakoitzean, dentsitate bikoitza','Masa bera zati bakoitzean, dentsitate txikiagoa'],'Masa eta bolumena batera txikitzen dira, eta zatidura mantentzen da.']],
    [1,['¿Por qué 100 g no identifican una sustancia?',['Distintas sustancias pueden tener esa masa','Toda sustancia tiene siempre 100 g','La masa no puede medirse con balanza','La masa solo existe en los sólidos'],'La masa es general y extensiva; no distingue por sí sola una sustancia.'],['Zergatik ez dute 100 g-k substantzia identifikatzen?',['Substantzia desberdinek masa hori izan dezakete','Substantzia guztiek beti 100 g dituzte','Masa ezin da balantzarekin neurtu','Masa solidoetan bakarrik dago'],'Masa orokorra eta estentsiboa da; bakarrik ez du substantzia bereizten.']],
    [2,['¿Qué error hay en decir 1 m² = 100 cm²?',['Se olvidó elevar al cuadrado el factor','Se utilizó un factor de masa','Se cambiaron litros por mililitros','Se usó la escala de temperatura'],'1 m = 100 cm, por eso 1 m² = 100 × 100 cm² = 10 000 cm².'],['Zer akats dago 1 m² = 100 cm² esatean?',['Faktorea karratura igotzea ahaztu da','Masaren faktorea erabili da','Litroak mililitroetara aldatu dira','Tenperaturaren eskala erabili da'],'1 m = 100 cm; beraz, 1 m² = 100 × 100 cm² = 10 000 cm².']],
    [2,['¿Cómo pasar de dam³ a L?',['dam³ → m³ y después m³ → L','dam³ → dam y después dam → L','dam³ → cm² y después cm² → L','dam³ → kg y después kg → L'],'1 dam³ = 1000 m³ y 1 m³ = 1000 L: factor total 1 000 000.'],['Nola pasa dam³ unitatetik L unitatera?',['dam³ → m³ eta gero m³ → L','dam³ → dam eta gero dam → L','dam³ → cm² eta gero cm² → L','dam³ → kg eta gero kg → L'],'1 dam³ = 1000 m³ eta 1 m³ = 1000 L: guztizko faktorea 1 000 000 da.']],
    [3,['¿Qué comparación es correcta: 1 kg de hierro y 1000 g de plumas?',['Igual masa, distinto volumen','Distinta masa, igual volumen','Igual masa e igual volumen','Distinta masa por usar gramos'],'1000 g son 1 kg. El hierro es más denso y ocupa menos volumen para la misma masa.'],['Zein konparazio da zuzena: 1 kg burdina eta 1000 g luma?',['Masa bera, bolumen desberdina','Masa desberdina, bolumen bera','Masa bera eta bolumen bera','Masa desberdina gramotan jartzeagatik'],'1000 g = 1 kg. Burdinak dentsitate handiagoa du eta masa berarekin bolumen txikiagoa hartzen du.']],
    [3,['¿Por qué puede flotar un barco muy pesado?',['Su densidad media es menor que la del agua','Su masa desaparece al entrar en agua','Todo objeto de metal flota por su color','El agua impide que el barco tenga volumen'],'El volumen exterior incluye espacios con aire: importa la densidad media, no solo la masa.'],['Zergatik flota dezake itsasontzi oso astun batek?',['Batez besteko dentsitatea urarena baino txikiagoa da','Masa desagertzen da uretan sartzean','Metalezko objektu guztiak koloreagatik flotatzen dira','Urak bolumena izatea eragozten dio'],'Kanpoko bolumenak airez betetako espazioak ditu: batez besteko dentsitatea da gakoa, ez masa bakarrik.']]
  ];
  reasoning.forEach(([topic,es,eu])=>pair(5,topic,es,eu));
  const relationships=[
    [['Si la masa se duplica y el volumen no cambia, la densidad…',['Se duplica','Se reduce a la mitad','No cambia','Se reduce a la cuarta parte'],'d = m/V: duplicar solo el numerador duplica el cociente.'],['Masa bikoiztu eta bolumena mantentzen bada, dentsitatea…',['Bikoizten da','Erdira murrizten da','Ez da aldatzen','Laurdenera murrizten da'],'d = m/V: zenbakitzailea bakarrik bikoiztean, zatidura bikoizten da.']],
    [['Si el volumen se duplica y la masa no cambia, la densidad…',['Se reduce a la mitad','Se duplica','No cambia','Se multiplica por cuatro'],'d = m/V: duplicar solo el denominador reduce el cociente a la mitad.'],['Bolumena bikoiztu eta masa mantentzen bada, dentsitatea…',['Erdira murrizten da','Bikoizten da','Ez da aldatzen','Lau aldiz handitzen da'],'d = m/V: izendatzailea bakarrik bikoiztean, zatidura erdira murrizten da.']],
    [['Dos cajas iguales contienen 5 kg y 20 kg. La segunda densidad es…',['Cuatro veces la primera','Dos veces la primera','Igual que la primera','La cuarta parte de la primera'],'Con igual volumen, la proporción de densidades es 20/5 = 4.'],['Bi kutxa berdinek 5 kg eta 20 kg dituzte. Bigarrenaren dentsitatea…',['Lehenengoarena halako lau da','Lehenengoarena halako bi da','Lehenengoaren berdina da','Lehenengoaren laurdena da'],'Bolumen bera izanda, dentsitateen erlazioa 20/5 = 4 da.']],
    [['Un objeto de densidad 0,8 g/cm³ se coloca en agua de 1 g/cm³. En el modelo sencillo…',['Flota por su menor densidad','Se hunde por su menor densidad','Flota porque no tiene masa','Se hunde porque no tiene volumen'],'Comparamos densidades medias: 0,8 es menor que 1.'],['0,8 g/cm³-ko objektu bat 1 g/cm³-ko uretan jartzen da. Eredu sinplean…',['Flotatzen du dentsitate txikiagoagatik','Hondoratzen da dentsitate txikiagoagatik','Flotatzen du masarik ez duelako','Hondoratzen da bolumenik ez duelako'],'Batez besteko dentsitateak alderatzen ditugu: 0,8 txikiagoa da 1 baino.']]
  ];
  relationships.forEach(([es,eu])=>pair(5,3,es,eu));
  return bank;
}
