export const unit = {
  cast: {title:'Materia y medida', subject:'Física y Química', topics:[
    {title:'La materia y sus cambios', summary:'Ciencia, materia, cuerpos y sistemas. Cambios físicos y químicos.', paragraphs:[
      'La ciencia busca explicar lo que ocurre mediante pruebas. Una afirmación científica debe poder contrastarse con observaciones o experimentos. Medir, comparar y repetir una experiencia ayuda a comprobar los resultados. Las ciencias físicas estudian, entre otros aspectos, la materia y la energía; las biológicas estudian los seres vivos; y las sociales, las sociedades y su comportamiento.',
      'La Física y la Química son dos ciencias relacionadas. La Física estudia fenómenos como el movimiento, el calor o los cambios de estado. La Química estudia la composición de las sustancias y las transformaciones que producen sustancias diferentes. La pregunta clave para distinguir un cambio físico de uno químico es: ¿se forman sustancias nuevas?',
      'Cuando un cubito de hielo se derrite, cambia de estado, pero sigue siendo agua. Es un cambio físico. Cortar un papel también es un cambio físico: cambia su forma, no la sustancia. Quemar el papel es un cambio químico, porque aparecen sustancias nuevas, como gases y cenizas. Algunos cambios físicos son reversibles, pero la reversibilidad por sí sola no sirve como regla absoluta. En una vela encendida hay dos procesos: la cera se funde, cambio físico, y parte de ella arde, cambio químico.',
      'La materia tiene masa y ocupa un volumen. El aire, aunque no lo veamos, es materia: ocupa espacio y tiene masa. Un globo con aire tiene más masa que ese mismo globo sin aire. Son materia un lápiz, el dióxido de carbono, el humo, el agua de un río, la arena y el algodón. La luz, el sonido y la pereza no son materia. La música transmite energía; no es una sustancia. Un archivo digital es información, aunque el dispositivo que lo almacena sí está hecho de materia.',
      'En el temario distinguimos cuerpos materiales y sistemas materiales. Un cuerpo tiene límites definidos, como un libro, un cubito de hielo o una silla. Para líquidos y gases usamos ejemplos de sistemas materiales, como el zumo, el aire o la atmósfera. Un recipiente puede delimitar un líquido o un gas; no debemos confundir el recipiente con su contenido.',
      'Para repasar, prueba estas tres preguntas antes de seguir. ¿Es materia el aire? Sí, tiene masa y ocupa volumen. ¿Es químico derretir hielo? No, sigue siendo agua. ¿Qué cambia cuando quemamos papel? Su composición: aparecen sustancias nuevas. Explicar el criterio es tan importante como acertar el nombre.'
    ]},
    {title:'Las propiedades de la materia', summary:'Cualitativas y cuantitativas; intensivas y extensivas; generales y características.', paragraphs:[
      'Las propiedades permiten describir y comparar la materia. No todas aportan la misma información. En esta unidad utilizamos tres clasificaciones distintas. Una misma propiedad recibe una etiqueta de cada clasificación: no hay que elegir entre cuantitativa, intensiva y característica, porque responden a preguntas diferentes.',
      'Primera pregunta: ¿se expresa con un número y una unidad, o describe una cualidad? Las propiedades cuantitativas se pueden medir: masa, volumen, temperatura o densidad. Las cualitativas describen aspectos como el color o la suavidad. Decir que una tela es blanca describe una cualidad. Decir que su longitud es de ciento cincuenta centímetros da una medida.',
      'Segunda pregunta: ¿depende de la cantidad de materia? Las propiedades extensivas dependen de ella. Al duplicar una muestra homogénea, se duplican su masa y su volumen. Las propiedades intensivas no dependen de la cantidad. Si dividimos agua a la misma temperatura, cada parte mantiene esa temperatura y la misma densidad. Comparamos siempre muestras en las mismas condiciones.',
      'Tercera pregunta: ¿sirve para ayudar a identificar una sustancia? Las propiedades generales, como masa y volumen, no bastan para identificarla. Dos materiales distintos pueden tener la misma masa. Las propiedades características, como densidad, solubilidad, dureza y temperatura de ebullición, ayudan a distinguir sustancias. Algunas dependen de las condiciones: por ejemplo, la temperatura de ebullición cambia con la presión.',
      'Siguiendo la clasificación del temario: la temperatura es cuantitativa, intensiva y general. El color y la suavidad son cualitativos, intensivos y generales. La temperatura de ebullición es cuantitativa, intensiva y característica. La dureza se trata como cuantitativa, intensiva y característica, porque puede compararse mediante escalas. La densidad y la solubilidad son cuantitativas, intensivas y características. El volumen es cuantitativo, extensivo y general.',
      'La solubilidad expresa cuánto soluto puede disolverse en un disolvente bajo condiciones determinadas. La dureza indica resistencia al rayado o a la deformación; en esta unidad la evaluamos con escalas. El estado físico puede describirse como sólido, líquido o gaseoso. En el texto del aceite, líquido indica estado; amarillo, color; insoluble en agua, solubilidad; los gramos por centímetro cúbico, densidad; los centímetros cúbicos, volumen; y los grados Celsius, temperatura.',
      'No confundas temperatura con temperatura de ebullición. La primera indica el estado térmico de la muestra en ese momento; la segunda señala a qué temperatura hierve una sustancia bajo una presión determinada. Una botella y un vaso de la misma agua pueden tener distinto volumen y la misma densidad.',
      'Método para responder: primero comprueba si hay medida o cualidad; después piensa qué pasaría al partir la muestra; por último decide si la propiedad ayuda a identificar la sustancia. Así puedes justificar cada etiqueta sin memorizar una lista de palabras sin sentido.'
    ]},
    {title:'Medir y convertir unidades', summary:'Magnitudes, Sistema Internacional, prefijos, superficies, volúmenes y litros.', paragraphs:[
      'Una magnitud es una propiedad que se puede medir. Medir consiste en comparar con una unidad de referencia. Una medida completa incluye un número y una unidad: decir cinco no basta; cinco metros describe una longitud. Elegimos el instrumento apropiado: una regla para longitud, una balanza para masa, un cronómetro para tiempo y un termómetro para temperatura.',
      'El Sistema Internacional permite comunicar medidas con unidades compartidas. Sus siete unidades básicas son: metro para longitud, kilogramo para masa, segundo para tiempo, kelvin para temperatura, amperio para intensidad de corriente eléctrica, mol para cantidad de sustancia y candela para intensidad luminosa. El símbolo del kelvin es K, sin signo de grados. Los símbolos no llevan plural: escribimos kg, no kgs. El volumen, la superficie y la densidad son magnitudes derivadas. En el Sistema Internacional se expresan en metros cúbicos, metros cuadrados y kilogramos por metro cúbico.',
      'Para las conversiones trabajaremos con kilo, hecto, deca, unidad, deci, centi y mili. En una escala de longitud, masa o capacidad, cada paso hacia una unidad menor multiplica por diez. Hacia una unidad mayor divide por diez. De kilogramos a gramos hay tres pasos: multiplicamos por mil. De kilogramos a miligramos hay seis: multiplicamos por un millón. Por eso cero coma cero ocho kilogramos equivalen a ochenta mil miligramos.',
      'En superficies cada paso multiplica o divide por cien. Un metro cuadrado contiene diez mil centímetros cuadrados, porque un metro tiene cien centímetros y cien por cien es diez mil. Ocho mil cuatrocientos cincuenta y seis centímetros cuadrados son cero coma ocho cuatro cinco seis metros cuadrados. No uses el factor cien de longitud para convertir metros cuadrados a centímetros cuadrados.',
      'En volúmenes cúbicos cada paso multiplica o divide por mil. Un metro cúbico equivale a mil decímetros cúbicos y a un millón de centímetros cúbicos. Aquí la escala tiene tres dimensiones. No confundas un metro, un metro cuadrado y un metro cúbico: miden magnitudes distintas.',
      'El litro es una unidad de capacidad que usamos habitualmente. Un litro equivale exactamente a un decímetro cúbico. Un mililitro equivale a un centímetro cúbico. Un metro cúbico equivale a mil litros. Así, ochocientos setenta y cinco mililitros equivalen a cero coma ocho siete cinco decímetros cúbicos. Para pasar de decámetros cúbicos a litros, primero puedes pasar a metros cúbicos y luego a litros: siete coma cinco decámetros cúbicos son siete mil quinientos metros cúbicos, es decir, siete millones quinientos mil litros.',
      'Para ordenar medidas, convierte todas a una misma unidad antes de comparar. Ocho coma dos decámetros son ochenta y dos metros; doscientos cincuenta y cuatro centímetros son dos coma cinco cuatro metros; cero coma cero cero cero tres kilómetros son cero coma tres metros. El mayor es el primero, después el segundo y después el tercero.',
      'En cada ejercicio escribe la equivalencia, calcula y añade la unidad final. Comprueba si el número debe aumentar o disminuir. Una unidad menor exige más unidades para describir la misma cantidad. El cambio de unidad no cambia la cantidad real.'
    ]},
    {title:'Densidad y flotación', summary:'Calcular densidad, masa y volumen. Comparar materiales y explicar la flotación.', paragraphs:[
      '¿Qué tiene más masa, un kilogramo de hierro o mil gramos de plumas? Tienen la misma masa. Lo que cambia es el volumen que ocupan. Las plumas ocupan mucho más espacio. Para comparar cuánto material hay en un mismo volumen usamos la densidad.',
      'La densidad es la masa dividida entre el volumen: densidad igual a masa entre volumen. Si dos cajas tienen el mismo volumen y una contiene cinco kilogramos mientras la otra contiene cero coma dos, la primera tiene veinticinco veces más densidad media. Si solo conocemos las masas y no los volúmenes, no podemos decidir cuál tiene más densidad.',
      'La densidad es cuantitativa, intensiva y característica. En una sustancia homogénea, bajo las mismas condiciones, no cambia por tomar una muestra mayor. Al duplicar masa y volumen a la vez, el cociente se mantiene. La unidad del Sistema Internacional es el kilogramo por metro cúbico. También usaremos gramos por centímetro cúbico. Un gramo por centímetro cúbico equivale a mil kilogramos por metro cúbico.',
      'Vamos a calcular. Una muestra tiene cuarenta gramos de masa y veinte centímetros cúbicos de volumen. Dividimos cuarenta entre veinte: su densidad es dos gramos por centímetro cúbico. Si conocemos densidad y volumen, multiplicamos: masa igual a densidad por volumen. Una sustancia de densidad dos gramos por centímetro cúbico que ocupa treinta centímetros cúbicos tiene sesenta gramos de masa. Si conocemos masa y densidad, dividimos: volumen igual a masa entre densidad. Sesenta gramos divididos entre dos gramos por centímetro cúbico dan treinta centímetros cúbicos.',
      'Antes de operar, revisa las unidades. No dividas sin más una masa en kilogramos entre un volumen en centímetros cúbicos si te piden gramos por centímetro cúbico. Convierte la masa a gramos, o transforma ambas magnitudes a las unidades del Sistema Internacional. Un kilogramo y quinientos centímetros cúbicos corresponden a mil gramos divididos entre quinientos: dos gramos por centímetro cúbico.',
      'La flotación depende de comparar la densidad media del objeto con la del fluido. En un modelo sencillo, un objeto menos denso que el agua flota y uno más denso se hunde. Si tienen igual densidad, puede quedar suspendido. El hielo es menos denso que el agua líquida y por eso flota. El aceite habitual es menos denso que el agua; además, no se mezcla con ella, de modo que queda encima.',
      'El principio de Arquímedes explica el empuje. Todo cuerpo total o parcialmente sumergido en un fluido recibe una fuerza vertical hacia arriba igual al peso del fluido que desplaza. El peso del cuerpo actúa hacia abajo. Cuando un objeto flota en equilibrio, el empuje compensa su peso. No confundas masa con peso: la masa es cantidad de materia y se mide en kilogramos; el peso es una fuerza. No necesitamos cálculos de fuerzas para esta unidad, pero sí comprender la dirección del empuje y qué fluido se desplaza.',
      'No basta con decir que un objeto pesado se hunde. Un barco puede tener mucha masa y flotar porque su volumen exterior incluye espacios con aire y su densidad media es baja. Lo importante es la relación entre masa y volumen. Al terminar, comprueba la fórmula, las unidades y si el resultado tiene sentido.'
    ]}
  ]},
  eus: {title:'Materia eta neurketa', subject:'Fisika eta Kimika', topics:[
    {title:'Materia eta haren aldaketak', summary:'Zientzia, materia, gorputzak eta sistemak. Aldaketa fisikoak eta kimikoak.', paragraphs:[
      'Zientziak gertatzen dena frogen bidez azaldu nahi du. Baieztapen zientifiko bat behaketen edo esperimentuen bidez egiaztatu ahal izan behar da. Neurtzeak, alderatzeak eta esperimentua errepikatzeak emaitzak egiaztatzen laguntzen dute. Zientzia fisikoek materia eta energia aztertzen dituzte, besteak beste. Zientzia biologikoek izaki bizidunak aztertzen dituzte; gizarte zientziek, gizarteak eta haien portaera.',
      'Fisika eta Kimika elkarrekin lotutako bi zientzia dira. Fisikak mugimendua, beroa eta egoera aldaketak bezalako fenomenoak aztertzen ditu. Kimikak substantzien osaera eta substantzia berriak sortzen dituzten eraldaketak aztertzen ditu. Aldaketa fisikoa eta kimikoa bereizteko galdera nagusia hau da: substantzia berririk sortzen al da?',
      'Izotz kubo bat urtzen denean, egoera aldatzen da, baina ura izaten jarraitzen du. Aldaketa fisikoa da. Papera moztea ere aldaketa fisikoa da: forma aldatzen da, ez substantzia. Papera erretzea aldaketa kimikoa da, gasak eta errautsak bezalako substantzia berriak sortzen direlako. Aldaketa fisiko batzuk itzulgarriak dira, baina itzulgarritasuna bakarrik ez da beti irizpide nahikoa. Piztutako kandela batean bi prozesu daude: argizaria urtzea aldaketa fisikoa da, eta erretzea aldaketa kimikoa.',
      'Materiak masa du eta bolumena hartzen du. Airea, ikusten ez badugu ere, materia da: espazioa hartzen du eta masa du. Airez betetako puxika batek hutsik dagoen puxika berak baino masa handiagoa du. Arkatza, karbono dioxidoa, kea, ibai bateko ura, harea eta kotoia materia dira. Argia, soinua eta alferkeria ez dira materia. Musikak energia transmititzen du, baina ez da substantzia. Fitxategi digital bat informazioa da; hura gordetzen duen gailua, ordea, materiaz egina dago.',
      'Temarioan gorputz materialak eta sistema materialak bereizten ditugu. Gorputz batek muga zehatzak ditu, liburu batek, izotz kubo batek edo aulki batek bezala. Likidoetarako eta gasetarako sistema materialen adibideak erabiltzen ditugu, hala nola zukua, airea eta atmosfera. Ontzi batek likido edo gas bat mugatu dezake; ontzia eta barruko edukia ez dira gauza bera.',
      'Jarraitu aurretik, erantzun hiru galdera hauei. Airea materia al da? Bai, masa du eta bolumena hartzen du. Izotza urtzea aldaketa kimikoa al da? Ez, ura izaten jarraitzen du. Zer aldatzen da papera erretzean? Osaera: substantzia berriak sortzen dira. Erantzunaren izena asmatzea bezain garrantzitsua da irizpidea azaltzea.'
    ]},
    {title:'Materiaren propietateak', summary:'Kualitatiboak eta kuantitatiboak; intentsiboak eta estentsiboak; orokorrak eta bereizgarriak.', paragraphs:[
      'Propietateek materia deskribatzeko eta alderatzeko balio dute. Propietate guztiek ez dute informazio bera ematen. Unitate honetan hiru sailkapen erabiltzen ditugu. Propietate berak sailkapen bakoitzeko etiketa bat du. Ez dugu kuantitatiboa, intentsiboa edo bereizgarria aukeren artean bakarra hautatu behar: galdera desberdinei erantzuten diete.',
      'Lehenengo galdera: zenbaki eta unitate batez adierazten da, edo nolakotasun bat deskribatzen du? Propietate kuantitatiboak neurtu daitezke: masa, bolumena, tenperatura edo dentsitatea. Propietate kualitatiboek kolorea edo leuntasuna bezalako ezaugarriak deskribatzen dituzte. Oihal bat zuria dela esatea nolakotasun bat deskribatzea da. Haren luzera ehun eta berrogeita hamar zentimetrokoa dela esatea neurri bat ematea da.',
      'Bigarren galdera: materia kantitatearen araberakoa da? Propietate estentsiboak kantitatearen araberakoak dira. Lagin homogeneo bat bikoiztean, masa eta bolumena bikoizten dira. Propietate intentsiboak ez dira kantitatearen araberakoak. Tenperatura berean dagoen ura zatitzen badugu, zati bakoitzak tenperatura eta dentsitate bera mantentzen ditu. Laginak baldintza beretan alderatzen ditugu.',
      'Hirugarren galdera: substantzia identifikatzen laguntzen du? Propietate orokorrak, masa eta bolumena adibidez, ez dira nahikoak substantzia identifikatzeko. Material desberdinek masa bera izan dezakete. Propietate bereizgarriek, dentsitateak, disolbagarritasunak, gogortasunak eta irakite tenperaturak, substantziak bereizten laguntzen dute. Batzuk baldintzen araberakoak dira: irakite tenperatura, adibidez, presioarekin aldatzen da.',
      'Temarioaren sailkapenaren arabera, tenperatura kuantitatiboa, intentsiboa eta orokorra da. Kolorea eta leuntasuna kualitatiboak, intentsiboak eta orokorrak dira. Irakite tenperatura kuantitatiboa, intentsiboa eta bereizgarria da. Gogortasuna kuantitatibotzat hartzen dugu, eskalen bidez alderatu daitekeelako; intentsiboa eta bereizgarria ere bada. Dentsitatea eta disolbagarritasuna kuantitatiboak, intentsiboak eta bereizgarriak dira. Bolumena kuantitatiboa, estentsiboa eta orokorra da.',
      'Disolbagarritasunak baldintza jakinetan disolbatzaile batean zenbat solutu disolba daitekeen adierazten du. Gogortasunak urraduraren edo deformazioaren aurkako erresistentzia adierazten du; unitate honetan eskalen bidez ebaluatzen dugu. Egoera fisikoa solidoa, likidoa edo gasa izan daiteke. Olioaren testuan, likidoak egoera adierazten du; horiak, kolorea; uretan disolbaezinak, disolbagarritasuna; gramo zentimetro kubikoko unitateak, dentsitatea; zentimetro kubikoek, bolumena; eta Celsius graduek, tenperatura.',
      'Ez nahastu tenperatura eta irakite tenperatura. Lehenengoak laginak une horretan duen egoera termikoa adierazten du. Bigarrenak substantzia batek presio jakin batean zer tenperaturatan irakiten duen adierazten du. Ur beraren botila batek eta edalontzi batek bolumen desberdina eta dentsitate bera izan ditzakete.',
      'Erantzuteko metodoa: lehenik, begiratu neurria edo nolakotasuna den. Gero, pentsatu zer gertatuko litzatekeen lagina zatitzean. Azkenik, erabaki propietateak substantzia identifikatzen laguntzen duen. Horrela etiketa bakoitza arrazoitu ahal izango duzu, hitz zerrenda bat buruz ikasi beharrean.'
    ]},
    {title:'Neurtzea eta unitateak bihurtzea', summary:'Magnitudeak, Nazioarteko Sistema, aurrizkiak, azalerak, bolumenak eta litroak.', paragraphs:[
      'Magnitudea neurtu daitekeen propietatea da. Neurtzea erreferentzia unitate batekin alderatzea da. Neurri oso batek zenbaki bat eta unitate bat ditu. Bost esatea ez da nahikoa; bost metro esateak luzera adierazten du. Tresna egokia aukeratzen dugu: erregela luzerarako, balantza masarako, kronometroa denborarako eta termometroa tenperaturarako.',
      'Nazioarteko Sistemak neurriak unitate komunekin adierazteko balio du. Oinarrizko zazpi unitateak hauek dira: metroa luzerarako, kilogramoa masarako, segundoa denborarako, kelvina tenperaturarako, amperea korronte elektrikoaren intentsitaterako, mola substantzia kantitaterako eta kandela argi intentsitaterako. Kelvinaren ikurra K da, gradu ikurrik gabe. Ikurrek ez dute pluralik. Bolumena, azalera eta dentsitatea magnitude eratorriak dira. Nazioarteko Sisteman metro kubiko, metro karratu eta kilogramo metro kubikoko unitateetan adierazten dira.',
      'Bihurketetarako kilo, hekto, deka, unitatea, dezi, zenti eta mili erabiliko ditugu. Luzera, masa edo edukieraren eskalan, unitate txikiago batera urrats bat egitean hamarrez biderkatzen dugu. Handiago batera joatean, hamarrez zatitzen dugu. Kilogramotik gramora hiru urrats daude: milaz biderkatzen dugu. Kilogramotik miligramora sei urrats daude: milioi batez biderkatzen dugu. Beraz, zero koma zero zortzi kilogramo laurogei mila miligramo dira.',
      'Azaleretan, urrats bakoitzean ehunez biderkatzen edo zatitzen dugu. Metro karratu batean hamar mila zentimetro karratu daude. Metro batek ehun zentimetro ditu eta ehun bider ehun hamar mila da. Zortzi mila laurehun eta berrogeita hamasei zentimetro karratu zero koma zortzi lau bost sei metro karratu dira. Ez erabili luzerarako faktorea azalerak bihurtzeko.',
      'Bolumen kubikoetan, urrats bakoitzean milaz biderkatzen edo zatitzen dugu. Metro kubiko bat mila dezimetro kubiko eta milioi bat zentimetro kubiko dira. Eskalak hiru dimentsio ditu. Ez nahastu metroa, metro karratua eta metro kubikoa: magnitude desberdinak neurtzen dituzte.',
      'Litroa egunero erabiltzen dugun edukiera unitatea da. Litro bat dezimetro kubiko baten berdina da, zehazki. Mililitro bat zentimetro kubiko bat da. Metro kubiko bat mila litro da. Horrela, zortziehun eta hirurogeita hamabost mililitro zero koma zortzi zazpi bost dezimetro kubiko dira. Dekametro kubikoetatik litroetara pasatzeko, lehenik metro kubikoetara pasa gaitezke eta gero litroetara. Zazpi koma bost dekametro kubiko zazpi mila eta bostehun metro kubiko dira, hau da, zazpi milioi eta bostehun mila litro.',
      'Neurriak ordenatzeko, bihurtu denak unitate berera alderatu aurretik. Zortzi koma bi dekametro laurogeita bi metro dira. Berrehun eta berrogeita hamalau zentimetro bi koma bost lau metro dira. Zero koma zero zero zero hiru kilometro zero koma hiru metro dira. Lehenengoa da handiena, gero bigarrena eta azkenik hirugarrena.',
      'Ariketa bakoitzean idatzi baliokidetasuna, kalkulatu eta jarri azken unitatea. Egiaztatu zenbakia handitu edo txikitu behar den. Unitate txikiagoa erabiltzean, unitate gehiago behar ditugu kantitate bera adierazteko. Unitatea aldatzeak ez du benetako kantitatea aldatzen.'
    ]},
    {title:'Dentsitatea eta flotazioa', summary:'Dentsitatea, masa eta bolumena kalkulatzea. Materialak alderatzea eta flotazioa azaltzea.', paragraphs:[
      'Zerk du masa handiagoa: kilogramo bat burdinak edo mila gramo lumak? Masa bera dute. Aldatzen dena hartzen duten bolumena da. Lumek askoz espazio gehiago hartzen dute. Bolumen berean zenbat materia dagoen alderatzeko dentsitatea erabiltzen dugu.',
      'Dentsitatea masa zati bolumena da. Bi kutxek bolumen bera badute eta batek bost kilogramo eta besteak zero koma bi kilogramo baditu, lehenengoaren batez besteko dentsitatea hogeita bost aldiz handiagoa da. Masak bakarrik ezagutzen baditugu, bolumenak jakin gabe, ezin dugu dentsitate handiena zeinek duen erabaki.',
      'Dentsitatea kuantitatiboa, intentsiboa eta bereizgarria da. Substantzia homogeneo batean, baldintza beretan, ez da aldatzen lagin handiago bat hartzeagatik. Masa eta bolumena batera bikoiztean, zatidura bera mantentzen da. Nazioarteko Sistemako unitatea kilogramo metro kubikoko da. Gramo zentimetro kubikoko unitatea ere erabiliko dugu. Gramo bat zentimetro kubikoko mila kilogramo metro kubikoko dira.',
      'Kalkulatu dezagun. Lagin batek berrogei gramoko masa eta hogei zentimetro kubikoko bolumena ditu. Berrogei zati hogei eginez, dentsitatea bi gramo zentimetro kubikoko da. Dentsitatea eta bolumena ezagutzen baditugu, biderkatzen dugu: masa berdin dentsitatea bider bolumena. Bi gramo zentimetro kubikoko dentsitatea duen substantziak hogeita hamar zentimetro kubiko hartzen baditu, hirurogei gramoko masa du. Masa eta dentsitatea ezagutzen baditugu, zatitzen dugu: bolumena berdin masa zati dentsitatea. Hirurogei gramo zati bi gramo zentimetro kubikoko eginez, hogeita hamar zentimetro kubiko lortzen ditugu.',
      'Eragiketak egin aurretik, begiratu unitateak. Ez zatitu zuzenean kilogramoko masa zentimetro kubikoko bolumenarekin, emaitza gramo zentimetro kubikoko eskatzen badizute. Bihurtu masa gramotara, edo bi magnitudeak Nazioarteko Sistemako unitateetara. Kilogramo bat mila gramo dira. Bostehun zentimetro kubikoko bolumenarekin, mila zati bostehun eginez, bi gramo zentimetro kubikoko lortzen dugu.',
      'Flotazioa ulertzeko, objektuaren batez besteko dentsitatea fluidoaren dentsitatearekin alderatzen dugu. Eredu sinple batean, ura baino dentsitate txikiagoa duen objektua flotatu egiten da; handiagoa duena hondoratu egiten da. Dentsitate bera badute, esekita gera daiteke. Izotzak ur likidoak baino dentsitate txikiagoa du, eta horregatik flotatzen du. Ohiko olioak urak baino dentsitate txikiagoa du. Gainera, ez da urarekin nahasten; horregatik geratzen da gainean.',
      'Arkimedesen printzipioak bultzada azaltzen du. Fluido batean guztiz edo partzialki murgildutako gorputz orok goranzko indar bertikal bat jasaten du, desplazatutako fluidoaren pisuaren berdina. Gorputzaren pisuak beherantz eragiten du. Objektua flotatzen eta orekan dagoenean, bultzadak pisua orekatzen du. Ez nahastu masa eta pisua: masa materia kantitatea da eta kilogramotan neurtzen da; pisua indarra da. Unitate honetan ez dugu indarren kalkulurik behar, baina bultzadaren norabidea eta desplazatutako fluidoa ulertu behar ditugu.',
      'Ez da nahikoa objektu astun bat hondoratzen dela esatea. Itsasontzi batek masa handia izan eta flotatu egin dezake, kanpoko bolumenak airez betetako espazioak hartzen dituelako eta batez besteko dentsitatea txikia delako. Garrantzitsuena masa eta bolumenaren arteko erlazioa da. Amaieran egiaztatu formula, unitateak eta emaitza zentzuzkoa den.'
    ]}
  ]}
};

export const properties = [
  {name:['Masa','Masa'],type:0,amount:1,identity:0},
  {name:['Temperatura','Tenperatura'],type:0,amount:0,identity:0},
  {name:['Color','Kolorea'],type:1,amount:0,identity:0},
  {name:['Suavidad','Leuntasuna'],type:1,amount:0,identity:0},
  {name:['Temperatura de ebullición','Irakite tenperatura'],type:0,amount:0,identity:1},
  {name:['Dureza (medida en una escala)','Gogortasuna (eskala batean neurtuta)'],type:0,amount:0,identity:1},
  {name:['Densidad','Dentsitatea'],type:0,amount:0,identity:1},
  {name:['Volumen','Bolumena'],type:0,amount:1,identity:0},
  {name:['Solubilidad','Disolbagarritasuna'],type:0,amount:0,identity:1}
];
export const baseUnits = [
  ['Longitud','Luzera','m','Metro','Metroa'],['Masa','Masa','kg','Kilogramo','Kilogramoa'],
  ['Tiempo','Denbora','s','Segundo','Segundoa'],['Temperatura','Tenperatura','K','Kelvin','Kelvina'],
  ['Intensidad de corriente','Korronte intentsitatea','A','Amperio','Amperea'],
  ['Cantidad de sustancia','Substantzia kantitatea','mol','Mol','Mola'],
  ['Intensidad luminosa','Argi intentsitatea','cd','Candela','Kandela']
];

export const propertyDefinitions = {
 cast:[
  ['Cuantitativa','Se puede medir y expresar con un valor numérico y, cuando corresponda, una unidad.','Ejemplo: masa = 30 g.'],
  ['Cualitativa','Describe una cualidad sin dar una medida numérica.','Ejemplo: color amarillo.'],
  ['Intensiva','No depende de la cantidad de materia, comparando la misma sustancia en iguales condiciones.','Ejemplo: densidad del agua.'],
  ['Extensiva','Depende de la cantidad de materia.','Ejemplo: masa y volumen.'],
  ['General','No permite identificar por sí sola una sustancia; distintos materiales pueden compartir su valor.','Ejemplo: dos sustancias pueden tener 30 g.'],
  ['Característica','Ayuda a distinguir o identificar sustancias cuando se comparan en condiciones fijadas.','Ejemplo: densidad o temperatura de ebullición.']
 ],
 eus:[
  ['Kuantitatiboa','Neurtu eta zenbakizko balio batez eta, dagokionean, unitate batez adierazi daiteke.','Adibidea: masa = 30 g.'],
  ['Kualitatiboa','Nolakotasun bat deskribatzen du, zenbakizko neurririk eman gabe.','Adibidea: kolore horia.'],
  ['Intentsiboa','Ez da materia kantitatearen araberakoa, substantzia bera baldintza beretan alderatuz.','Adibidea: uraren dentsitatea.'],
  ['Estentsiboa','Materia kantitatearen araberakoa da.','Adibidea: masa eta bolumena.'],
  ['Orokorra','Bakarrik ez du substantzia identifikatzen; material desberdinek balio bera izan dezakete.','Adibidea: bi substantziak 30 g izan ditzakete.'],
  ['Bereizgarria','Baldintza finkoetan alderatuz, substantziak bereizten edo identifikatzen laguntzen du.','Adibidea: dentsitatea edo irakite tenperatura.']
 ]
};
export const review = {
 cast:[
  'Resumen del bloque uno. La ciencia se apoya en pruebas. La materia tiene masa y volumen. Un cambio físico conserva la sustancia; un cambio químico produce sustancias nuevas. Ahora, examen oral: pausa después de cada pregunta. ¿Por qué el aire es materia? ¿Qué diferencia cortar y quemar papel? ¿Qué dos cambios hay en una vela? ¿Qué diferencia un archivo digital de su soporte? ¿Cómo distingues botella y contenido? Comprueba: aire tiene masa y volumen; cortar es físico y quemar químico; la vela funde y quema cera; el archivo es información y el soporte es material; la botella es cuerpo y el agua se estudia como sistema.',
  'Resumen del bloque dos. Cuantitativa se mide; cualitativa describe una cualidad. Extensiva depende de la cantidad; intensiva no, en iguales condiciones. General no identifica por sí sola; característica ayuda a identificar. Examen oral: pausa y responde. Define las seis etiquetas con un ejemplo. Clasifica masa, color, volumen y densidad con tres etiquetas. ¿Por qué temperatura no es lo mismo que temperatura de ebullición? Comprueba: masa y volumen son cuantitativos, extensivos y generales; color es cualitativo, intensivo y general; densidad es cuantitativa, intensiva y característica. La temperatura actual no identifica la sustancia; su punto de ebullición a una presión fija ayuda a distinguirla.',
  'Resumen del bloque tres. Una magnitud se puede medir. Una medida lleva número y unidad. En unidades lineales y litros, cada salto tiene factor diez; en superficies, cien; en volúmenes cúbicos, mil. Un litro es un decímetro cúbico y un mililitro un centímetro cúbico. Examen oral: pausa y responde. ¿Cuál es la unidad básica de masa? ¿Qué instrumento mide temperatura? ¿Por qué no se convierte un área como una longitud? ¿Qué haces antes de ordenar unidades distintas? Comprueba: kilogramo, termómetro, dos dimensiones y convertir todas a la misma unidad.',
  'Resumen del bloque cuatro. Densidad es masa entre volumen; masa es densidad por volumen; volumen es masa entre densidad. Antes de calcular, compatibiliza unidades. La densidad media permite comparar un objeto con un fluido. Arquímedes explica el empuje hacia arriba, igual al peso del fluido desplazado. Examen oral: pausa y responde. ¿Basta la masa para comparar densidad? ¿Por qué flota el hielo? ¿Por qué flota un barco de metal? ¿Qué cambia al dividir una muestra homogénea? Comprueba: necesitas volumen; el hielo es menos denso que agua líquida; el barco incluye aire y tiene baja densidad media; bajan masa y volumen, pero no densidad si se mantienen condiciones.'
 ],
 eus:[
  'Lehen blokearen laburpena. Zientzia frogetan oinarritzen da. Materiak masa eta bolumena ditu. Aldaketa fisikoak substantzia mantentzen du; aldaketa kimikoak substantzia berriak sortzen ditu. Orain, ahozko azterketa: gelditu galdera bakoitzaren ondoren. Zergatik da airea materia? Zer alde dago papera moztearen eta erretzearen artean? Zer bi aldaketa daude kandela batean? Zer alde dago fitxategi digitalaren eta euskarriaren artean? Nola bereizten dituzu botila eta edukia? Egiaztatu: aireak masa eta bolumena ditu; moztea fisikoa da eta erretzea kimikoa; kandelak argizaria urtu eta erretzen du; fitxategia informazioa da eta euskarria materiala; botila gorputza da eta ura sistema gisa aztertzen da.',
  'Bigarren blokearen laburpena. Kuantitatiboa neurtzen da; kualitatiboak nolakotasuna deskribatzen du. Estentsiboa kantitatearen araberakoa da; intentsiboa ez, baldintza beretan. Orokorrak bakarrik ez du identifikatzen; bereizgarriak identifikatzen laguntzen du. Ahozko azterketa: gelditu eta erantzun. Definitu sei etiketak adibide batekin. Sailkatu masa, kolorea, bolumena eta dentsitatea hiru etiketarekin. Zergatik ez dira tenperatura eta irakite tenperatura gauza bera? Egiaztatu: masa eta bolumena kuantitatiboak, estentsiboak eta orokorrak dira; kolorea kualitatiboa, intentsiboa eta orokorra da; dentsitatea kuantitatiboa, intentsiboa eta bereizgarria da. Uneko tenperaturak ez du substantzia identifikatzen; presio finko bateko irakite puntuak bereizten laguntzen du.',
  'Hirugarren blokearen laburpena. Magnitudea neurtu daiteke. Neurriak zenbakia eta unitatea ditu. Unitate linealetan eta litroetan, urrats bakoitzeko faktorea hamar da; azaleretan, ehun; bolumen kubikoetan, mila. Litro bat dezimetro kubiko bat da, eta mililitro bat zentimetro kubiko bat. Ahozko azterketa: gelditu eta erantzun. Zein da masaren oinarrizko unitatea? Zer tresnak neurtzen du tenperatura? Zergatik ez da azalera luzera bezala bihurtzen? Zer egiten duzu unitate desberdinak ordenatu aurretik? Egiaztatu: kilogramoa, termometroa, bi dimentsio eta denak unitate berera bihurtzea.',
  'Laugarren blokearen laburpena. Dentsitatea masa zati bolumena da; masa dentsitatea bider bolumena da; bolumena masa zati dentsitatea da. Kalkulatu aurretik, egin unitateak bateragarri. Batez besteko dentsitateak objektua fluidoarekin alderatzen uzten du. Arkimedesek goranzko bultzada azaltzen du, desplazatutako fluidoaren pisuaren berdina. Ahozko azterketa: gelditu eta erantzun. Masa nahikoa al da dentsitatea alderatzeko? Zergatik flotatzen du izotzak? Zergatik flotatzen du metalezko itsasontziak? Zer aldatzen da lagin homogeneoa zatitzean? Egiaztatu: bolumena behar duzu; izotzak ur likidoak baino dentsitate txikiagoa du; itsasontziak airea dauka eta batez besteko dentsitate txikia du; masa eta bolumena txikitzen dira, baina dentsitatea ez, baldintzak mantentzen badira.'
 ]
};
for(const lang of ['cast','eus'])unit[lang].topics.forEach((topic,i)=>topic.paragraphs.push(review[lang][i]));
export const audioFile=(lang,topic)=>`fiki-u1-${String(topic+1).padStart(2,'0')}-${lang}-r2.mp3`;
